# Generated by Django 4.2 on 2023-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='DateOfBirth',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='MobileNumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
