# Generated by Django 4.2 on 2023-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Rollno',
        ),
        migrations.AddField(
            model_name='student',
            name='Rollnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='MobileNumber',
            field=models.BigIntegerField(),
        ),
    ]
